### ISSUE TITLE
Develop API controllers for each model

### ISSUE THREAD

**Issue by UniverseVoids** [richaidos/Medical-Shop-MVC#9]

**Comment by UniverseVoids** [comment]
API for authorization (maybe with tokken, using oauth).
API for CRUD, to each model.
API for search information, that have two parameters (String SearchBy, String SearchValue)
**SearchBy :**
- SearchBy == "Medicine"
   - by name
   - by description
- SearchBy == "Doctor"
   - by name
   - by surname
   - by specialization name
   - by specialization description
- SearchBy == "Pharmacy"
   - by name
   - by address
   - by phone
- SearchBy == "MedEnterprise"
   - by name
   - by address
   - by description

**Comment by richaidos** [comment]
API Version `https://localhost:44389/api/search?SearchBy=Medecine&SearchValue=лол`

**Comment by richaidos** [comment]
- `localhost:44389/api/medicine` - Медикаменты и их описание
  - Method: **GET** возвращает все медикаменты
  - Method: **GET** **/api/medicine/id** получить определенный медикамент по id

- 

`localhost:44389/api/Doctor`
`localhost:44389/api/MedEnterprise`
`localhost:44389/api/pharmacie`
`localhost:44389/api/specialization`
`localhost:44389/api/user` - Authorization
